name = "Newb Firelight Lite"
version = [0, 1, 9]
min_supported_mc_version = [1, 21, 20]
description = '''
ยงc%w
ยง7- An enchanced vanilla shader for Minecraft!
%v
ยง3https://devendrn.github.io/newb-shader/
''' # %w = patch warning, %v = version
authors = ["JC GAMING7125","devendrn"]
url = "https://devendrn.github.io/newb-shader/"
uuid = "7f78fde3-f4b2-4e05-b3e0-5c37cd334aae" # Use https://www.uuidgenerator.net/version4
materials = ["Sky", "LegacyCubemap", "Clouds", "EndSky", "SunMoon", "RenderChunk", "Actor"]

[info] 
copyright = '''
Copyright (c) %a

**Important Note:** Redistribution of this resource pack with links other than the official ones provided by the creator is strictly prohibited.
''' # %a = authors
credits = '''
'''

# subpacks are arranged in left to right order
# right-most subpack is enabled by default

[[subpack]]
define = "DEFAULT"
materials = []
description = '''
Default
'''

